### ISSUE TITLE
Agregar seguridad al admin

### ISSUE THREAD

**Issue by Zeeerooo** [niclabs/AdkintunMobile-Server#10]
Actualmente cualqueira peude acceder al admin. Eso debe mejorar.

**Comment by nanocatdemen** [comment]
Relacionado: https://flask-admin.readthedocs.org/en/latest/introduction/#authorization-permissions

**Comment by JoseTapiaG** [comment]
67ac927f983d4ba8ae1fefff2b05180e56ce0137 cierra #10
