### ISSUE TITLE
Definir que datos identifican un device en Android

### ISSUE THREAD

**Issue by JoseTapiaG** [niclabs/AdkintunMobile-Server#23]
En la versión antigua de adkintun se enviaban los siguientes datos:
brand
board
build_id
device
hardware
manufacturer
model
release
release_type
product
sdk
      
Es necesario definir que datos identifican un dispositivo para saber si ya está en la base de datos

**Comment by Zeeerooo** [comment]
El valor device_id identifica únicamente a cada dispositivo, por lo cual será lo necesario para validar la  existencia previa de un dispositivo antes de agregar uno nuevo.
