### ISSUE TITLE
Implementación de protocolo de autentificación para acceder a la API

### ISSUE THREAD

**Issue by Zeeerooo** [niclabs/AdkintunMobile-Server#31]
Implementar una comunicación autentificada entre la app android y el servidor web.

**Comment by madestro** [comment]
qué tiene de malo usar OAuth?

**Comment by Zeeerooo** [comment]
Oauth está pensado para autentificarse con aplicaciones mediante el uso de
un tercero, ejemplo Google, Facebook u otros, en los que ya se posee una
cuenta previa, y quien funciona como certificador por así decirlo, de la
persona a ingresar. Dado que los usuarios son anónimos, únicamente debemos
validar la relación app movil - server en cada envío de información.

**Comment by Zeeerooo** [comment]
App valida envío de datos mediante el uso de un token acordado mutuamente.

77653dab0513d771e3929a6515003410bdaa7b2a close #31
