### ISSUE TITLE
Implementar forma de crear y recuperar dumps de la BD

### ISSUE THREAD

**Issue by Zeeerooo** [niclabs/AdkintunMobile-Server#33]
La idea es tener una forma de crear dumps de tablas de la BD a json (en particular de telcos y antennas) y a su vez tener un método de volver a cargar dicha información a la BD en una nueva instancia del servidor.

**Comment by JoseTapiaG** [comment]
b8d61af156605b89f55b83ff507e16659bf555ed cierra #33
