### ISSUE TITLE
Implementar script que genere el reporte de datos

### ISSUE THREAD

**Issue by Zeeerooo** [niclabs/AdkintunMobile-Server#40]
La idea es generar un método que procese los datos obtenidos en un periodo de tiempo y los almacene en la tabla de informes.

**Comment by JoseTapiaG** [comment]
Falta agregar los subprocesos al método principal de guardado. Actualmente se pueden obtener los datos por separado, por ej, total de device por carrier.
Es necesario agregar un método que ejecute cada uno de estos subprocesos y que guarde en las tablas correspondientes de los reportes

**Comment by Zeeerooo** [comment]
Hay actualmente un problema con la ejecución de los jobs en el scheduler, dado que se duplicar las acciones. Eso debe repararse previo a su uso.

**Comment by Zeeerooo** [comment]
aa21ebcdb3a76e07bd0fdb30ab1406925c8443a8 close #40
