### ISSUE TITLE
Generar estadísticas generales

### ISSUE THREAD

**Issue by Zeeerooo** [niclabs/AdkintunMobile-Server#49]
Generar método que calcule:
- Total de equipos que han entregado datos
- Total de sims registradas
- Total de mediciones de señal registradas (GSM)
- Equipos por compañía
- Sims por compañía
- Mediciones efectuadas por compañía

**Comment by JoseTapiaG** [comment]
6af9db82e739e34c434159a1ba332aa3bb0eb8d6 cierra #49
