### ISSUE TITLE
Update Domain Configuration

### ISSUE THREAD

**Issue by sebablasko** [niclabs/adkintunmobile-server#87]
Currently the domain **adkintunmobile.cl** is not loading the page gh-pages of the github repository _AdkintunMobile-Server_. Apparently the active CNAME and DNS settings are now in the opposite of what was desired, because when someone visit www.adkintunmobile.cl it is loading an old version of the webpage (one with the signal map). The current version in gh-pages doesn't have any signal map and that is with which we are updating with the new info of the project.

**Comment by sebablasko** [comment]
Please, help us with this configuration @madestro

**Comment by Zeeerooo** [comment]
Now, www.adkintunmobile.cl must redirect to the gh-pages of the _AdkintunMobile_ repository. The gh-pages of _AdkintunMobile-Server_ will be deleted.
